# ====================================================================
# ÉTAPE 1 : Build (Compilation de l'application React)
# ====================================================================
FROM node:22-alpine

WORKDIR /app

# manifests
COPY package*.json ./
COPY frontend/package*.json ./frontend/
COPY shared/package*.json ./shared/

RUN npm install

# code (écrasé par les volumes)
COPY frontend ./frontend
COPY shared ./shared

WORKDIR /app/frontend

EXPOSE 5173
