FROM node:22-alpine

WORKDIR /app

# Installer les dépendances
COPY package*.json ./
COPY backend/package*.json ./backend/
COPY shared/package*.json ./shared/
RUN npm install --include=dev

# Copier tout le code (sera écrasé par les volumes si bind-mount)
COPY backend ./backend
COPY shared ./shared

WORKDIR /app/backend

EXPOSE 3000