import type { IFormProps } from "../../../organisms/Form";
import type { FormSubmitResult } from "../../../../types/FormSubmitResult";

export const profileDetailsFormData: IFormProps = {
  title: "Mes informations",
  type: "updateProfile",
  fields: [
    {
      kind: "base",
      id: "firstname",
      type: "text",
      placeholder: "",
      required: true,
      autoComplete: "given-name",
      label: "Prénom",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "lastname",
      type: "text",
      placeholder: "",
      required: true,
      autoComplete: "family-name",
      label: "Nom de famille",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "birthdate",
      type: "date",
      placeholder: "",
      required: true,
      autoComplete: "bday",
      label: "Date de naissance",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "addressStreet",
      type: "text",
      placeholder: "",
      required: true,
      autoComplete: "street-address",
      label: "Adresse",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "addressCity",
      type: "text",
      placeholder: "",
      required: true,
      autoComplete: "address-level2",
      label: "Ville",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "addressZip",
      type: "text",
      placeholder: "",
      required: true,
      autoComplete: "postal-code",
      label: "Code postal",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "addressCountry",
      type: "text",
      placeholder: "",
      required: true,
      autoComplete: "country-name",
      label: "Pays",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "phoneNumber",
      type: "tel",
      placeholder: "",
      required: true,
      autoComplete: "tel",
      label: "Numéro de téléphone",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "drivingLicense",
      type: "text",
      placeholder: "Ex : 123456789012",
      required: false,
      autoComplete: "",
      label: "N° de permis de conduire",
      onChange: () => {},
    },
  ],
  buttonContent: "Valider",
  onSubmit: async (): Promise<FormSubmitResult> => {
    return { ok: true };
  },
};

export const profileCredentialsFormData: IFormProps = {
  title: "Mes informations",
  type: "updateCredentials",
  fields: [
    {
      kind: "base",
      id: "email",
      type: "email",
      placeholder: "",
      required: true,
      autoComplete: "email",
      label: "Adresse e-mail*",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "oldPassword",
      type: "password",
      placeholder: "",
      required: true,
      autoComplete: "current-password",
      label: "Mot de passe actuel*",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "password",
      type: "password",
      placeholder: "",
      required: false,
      autoComplete: "new-password",
      label: "Nouveau mot de passe",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "confirmPassword",
      type: "password",
      placeholder: "",
      required: false,
      autoComplete: "new-password",
      label: "Confirmer le mot de passe",
      onChange: () => {},
    },
  ],
  buttonContent: "Valider",
  onSubmit: async (): Promise<FormSubmitResult> => {
    return { ok: true };
  },
};
