import type { IFormProps } from "../../../organisms/Form";
import type { FormSubmitResult } from "../../../../types/FormSubmitResult";
import { fetchCityByNameAndPostalCode } from "../../../../api/addressApi";

export const addVehicleFormData: IFormProps = {
  title: "Ajouter un véhicule",
  type: "addVehicle",
  fields: [
    {
      kind: "base",
      id: "categoryId",
      type: "select",
      required: true,
      label: "ID de catégorie",
      placeholder: "",
      value: "",
      options: [],
      onChange: () => {},
    },
    {
      kind: "base",
      id: "brand",
      type: "text",
      required: true,
      label: "Marque",
      placeholder: "Ex: Fiat",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "model",
      type: "text",
      required: true,
      label: "Modèle",
      placeholder: "Ex: Ducato",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "mileage",
      type: "number",
      required: true,
      label: "Kilométrage",
      placeholder: "Ex: 50000",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "registrationDate",
      type: "date",
      required: true,
      label: "Date d'immatriculation",
      placeholder: "",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "registrationPlate",
      type: "text",
      required: true,
      label: "Plaque d'immatriculation",
      placeholder: "Ex: AB123CD",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "description",
      type: "textarea",
      required: false,
      label: "Description",
      placeholder: "Description du véhicule",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "numberOfSeats",
      type: "number",
      required: true,
      label: "Nombre de sièges",
      step: "1",
      placeholder: "Ex: 4",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "numberOfSleepingPlaces",
      type: "number",
      required: true,
      label: "Places pour dormir",
      placeholder: "Ex: 2",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "length",
      type: "number",
      required: true,
      label: "Longueur (m)",
      step: "0.1",
      placeholder: "Ex: 6.5",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "height",
      type: "number",
      required: true,
      label: "Hauteur (m)",
      step: "0.1",
      placeholder: "Ex: 2.8",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "weight",
      type: "number",
      required: true,
      label: "Poids (kg)",
      step: "100",
      placeholder: "Ex: 3500",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "fuelType",
      type: "select",
      required: true,
      label: "Type de carburant",
      placeholder: "",
      value: "",
      options: [],
      onChange: () => {},
    },
    {
      kind: "base",
      id: "gearType",
      type: "select",
      required: true,
      label: "Type de transmission",
      placeholder: "",
      value: "",
      options: [],
      onChange: () => {},
    },
    {
      kind: "base",
      id: "consumption",
      type: "number",
      required: true,
      label: "Consommation (L/100km)",
      step: "0.1",
      placeholder: "Ex: 8.5",
      onChange: () => {},
    },
    {
      kind: "suggestion",
      id: "cityName",
      type: "text",
      placeholder: "Saisir la ville ou le code postal",
      required: true,
      autoComplete: "address-level2",
      label: "Ville",
      withSuggestions: true,
      fetchSuggestions: fetchCityByNameAndPostalCode,
      onChange: () => {},
    },
    {
      kind: "base",
      id: "insuranceNumber",
      type: "text",
      required: true,
      label: "Numéro d'assurance",
      placeholder: "Ex: 123456789",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "insuranceExpirationDate",
      type: "date",
      required: true,
      label: "Expiration de l'assurance",
      placeholder: "",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "basePrice",
      type: "number",
      required: true,
      label: "Prix journalier (€)",
      step: "0.1",
      placeholder: "Ex: 75",
      onChange: () => {},
    },
    {
      kind: "base",
      id: "equipmentIds",
      type: "select-multiple",
      required: false,
      label: "Équipements",
      placeholder: "",
      value: "",
      options: [],
      onChange: () => {},
    },
    {
      kind: "base",
      id: "isAvailable",
      type: "checkbox",
      required: false,
      label: "Disponible dès maintenant",
      checked: false,
      placeholder: "",
      onChange: () => {},
    },
  ],
  buttonContent: "Enregistrer",
  onSubmit: async (): Promise<FormSubmitResult> => {
    return { ok: true, errors: {} };
  },
};
